# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0006_auto_20161228_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessnumbers',
            name='band',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='blue',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='bonus',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='end_digit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='even',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='five',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='four',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='four_continue',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='gray',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='green',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='odd',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='one',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='one_continue',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='person',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='red',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='six',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='three',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='three_continue',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='total',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='two',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='two_continue',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='guessnumbers',
            name='yellow',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='guessnumbers',
            name='lottos',
            field=models.CharField(default='[1,2,3,4,five,6]', max_length=255),
        ),
        migrations.AlterField(
            model_name='guessnumbers',
            name='text',
            field=models.CharField(max_length=24),
        ),
    ]
