# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0008_guessnumbers_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='num_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('one', models.IntegerField(default=1)),
                ('two', models.IntegerField(default=1)),
                ('three', models.IntegerField(default=1)),
                ('four', models.IntegerField(default=1)),
                ('five', models.IntegerField(default=1)),
                ('six', models.IntegerField(default=1)),
                ('bonus', models.IntegerField(default=1)),
                ('person', models.IntegerField(default=1)),
                ('amount', models.CharField(default='1000', max_length=24)),
                ('total', models.IntegerField(default=1)),
                ('odd', models.IntegerField(default=1)),
                ('even', models.IntegerField(default=1)),
                ('yellow', models.IntegerField(default=1)),
                ('blue', models.IntegerField(default=1)),
                ('red', models.IntegerField(default=1)),
                ('green', models.IntegerField(default=1)),
                ('gray', models.IntegerField(default=1)),
                ('band', models.IntegerField(default=1)),
                ('one_continue', models.IntegerField(default=1)),
                ('two_continue', models.IntegerField(default=1)),
                ('three_continue', models.IntegerField(default=1)),
                ('four_continue', models.IntegerField(default=1)),
                ('end_digit', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='band',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='count',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='end_digit',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='even',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='five',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='four',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='four_continue',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='gray',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='green',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='one',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='one_continue',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='person',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='red',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='six',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='three',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='three_continue',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='total',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='two',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='two_continue',
        ),
        migrations.RemoveField(
            model_name='guessnumbers',
            name='yellow',
        ),
        migrations.AlterField(
            model_name='guessnumbers',
            name='lottos',
            field=models.CharField(default='[1,2,3,4,5,6]', max_length=255),
        ),
    ]
