# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0009_auto_20171112_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='nums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name=0)),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('four', models.IntegerField()),
                ('five', models.IntegerField()),
                ('six', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('person', models.IntegerField()),
                ('amount', models.CharField(default='1000', max_length=24)),
                ('total', models.IntegerField()),
                ('odd', models.IntegerField()),
                ('even', models.IntegerField()),
                ('yellow', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('red', models.IntegerField()),
                ('green', models.IntegerField()),
                ('gray', models.IntegerField()),
                ('band', models.IntegerField()),
                ('one_continue', models.IntegerField()),
                ('two_continue', models.IntegerField()),
                ('three_continue', models.IntegerField()),
                ('four_continue', models.IntegerField()),
                ('end_digit', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='num_history',
        ),
    ]
