# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0012_nums_shotting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nums',
            old_name='shotting_date',
            new_name='shotDate',
        ),
    ]
