# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0016_auto_20171121_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guessnumbers',
            options={'ordering': ['-update_date']},
        ),
        migrations.RenameField(
            model_name='guessnumbers',
            old_name='num_lotto',
            new_name='shoot_lotto',
        ),
    ]
