# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0017_auto_20171122_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessnumbers',
            name='lottos',
            field=models.TextField(default='[1,2,3,4,5,6]'),
        ),
    ]
