# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0018_auto_20171122_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decidednumbers',
            name='shotDate',
            field=models.DateField(db_index=True),
        ),
    ]
