# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0020_auto_20171122_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuessNumbers',
            new_name='ShootNumbers',
        ),
    ]
