# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0021_auto_20171122_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shootnumbers',
            name='name',
        ),
        migrations.AddField(
            model_name='shootnumbers',
            name='band',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shootnumbers',
            name='except_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shootnumbers',
            name='origin_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shootnumbers',
            name='predict_total_std',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='shootnumbers',
            name='predict_total_value',
            field=models.IntegerField(default=0),
        ),
    ]
