# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0023_auto_20171123_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootnumbers',
            name='predict_total_std',
            field=models.IntegerField(default=0),
        ),
    ]
