# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0024_auto_20171123_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootnumbers',
            name='except_nums',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shootnumbers',
            name='origin_nums',
            field=models.CharField(max_length=255),
        ),
    ]
