# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0025_auto_20171124_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shootnumbers',
            old_name='text',
            new_name='shooter',
        ),
    ]
