# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0027_auto_20171126_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootnumbers',
            name='shooter',
            field=models.CharField(max_length=255),
        ),
    ]
