# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0028_auto_20171126_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shootnumbers',
            old_name='shoot_lotto',
            new_name='shot_count',
        ),
    ]
