# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0029_auto_20171126_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootnumbers',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
