# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0030_auto_20171127_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooter', models.CharField(max_length=255)),
                ('shot_count', models.IntegerField(default=5)),
            ],
        ),
    ]
